Itertools count float input
tdakkota/sun pull request #12
Opened 2021-04-22 06:34 UTC by Algebra8

`itertools.count()` with float and int inputs, implemented with a recipe inspired by `1.` as described [here](https://github.com/tdakkota/sun/pull/10#issuecomment-824533105).

This PR is pretty large because more logic had to be changed than at first anticipated.

@tdakkota This works, as can be seen from the tests, but is pretty complicated (see [`add()`](https://github.com/tdakkota/sun/compare/master...Algebra8:itertools-count-float-input?expand=1#diff-a5603ce7f246714d7bc1f4c42adce50bab121847b739978af58c32bab1f5bb01R39)), and it's not clear what the downstream affects would be, e.g. `Hash()` still has to be implemented and I'm not sure how difficult this will become.

But it does work! 😄 

However, I'm open to slashing this PR in favor of using recipe `2.`, as long as we're ok with always returning a `starlark.Float`.

Curious to hear what you think.

2021-04-22 12:30 UTC, tdakkota commented on itertools.go
> +type countObject struct {
I think we can add a `counter` interface as abstraction for iterator state.
```go
type counter interface {
     Next() starlark.Value
     String() string
}

type intCounter struct {
        cnt, step starlark.Int
}

func (c intCounter) String() string { ... }
func (c intCounter) Next() starlark.Value { ... }

type floatCounter struct {
     cnt floatOrInt
     step starlark.Float
}

func (c floatCounter) String() string { ... }
func (c floatCounter) Next() starlark.Value { ... }

type countObject struct {
    state counter
    frozen bool
}

...
```

2021-04-22 21:41 UTC, Algebra8 commented on itertools.go
> +type countObject struct {
This definitely looks much clearer than my earlier implementation, thanks!

The thing I like a lot about this approach is that `floatCounter.cnt` is a `floatOrInt`, and this handles case 3, as shown below.
The only small issue is that I think `floatCounter.step` will also need to be a `floatOrInt` in order to handle case 4.
And if both `floatCounter.cnt` and `floatCounter.step` are `floatOrInt`, then doesn't that leave us in the same place?

cases for input types:
```python
# Case 1: int int
# Type of next will always be int.
# str is "count(0, 5)"
# Can use `intCounter`.
itertools.count(0, 5)

# Case 2: float float
# Type of next will always be a float.
# str is "count(0.5, 0.5)"
# Can use `floatCounter`.
itertools.count(0.5, 0.5)

# Case 3: int float
# Type of next will first be int then be float, since int + float = float.
# str is "count(5, 0.6)" then "count(5.6, 0.6)"
# Since `floatCounter.cnt` is `floatOrInt`, can use `floatCounter`.
itertools.count(5, 0.6)

# Case 4: float int
# Type of next will always be a float.
# str is "count(0.5, 5)"
# Can use `floatCounter`? Might need to update `floatCounter.step`.
itertools.count(0.5, 5)
```

Another thing to do is to have 4 separate structs:

```go

type intCounter struct {
        cnt, step starlark.Int
}

type floatCounter struct {
     cnt, step starlark.Float
}

type intFloatCounter struct {
     cnt floatOrInt
     step starlark.Float
}

type floatIntCounter struct {
     cnt starlark.Float
     step starlark.Int
}
```

Is this correct, or am I missing something?

2021-04-23 12:19 UTC, tdakkota commented on itertools.go
> +type countObject struct {
I think we can just convert `int` to the `float` in case `float int` before creating the object and use `floatCounter`.

2021-04-23 21:47 UTC, Algebra8 commented on itertools.go
> +type countObject struct {
Yeah we can do that but it will affect `str(count(float, int))`, it will print a float when we want an int.

2021-04-25 05:12 UTC, Algebra8 commented on itertools.go
> +type countObject struct {
In [this commit](https://github.com/tdakkota/sun/pull/12/commits/27ccb4c298d76ad7b349d0eb43592c8a3b05e7a2) I tried this once again by type casting the underlying `starlark.Value` interface instead of using pointers. I think it cleared it up a lot.

The benefit of using this implementation is that something like `str(count(0.5, 5))` will return the correct result:

```python
>>> itertools.count(0.5, 5)
count(0.5, 5)
```

but with the other implementation we would have:

```python
>>> itertools.count(0.5, 5)
count(0.5, 5.0)
```
Please take a look and if you don't like it then I would be more than happy to revert to the changes that you recommended above :)

2021-04-25 06:02 UTC, tdakkota requested changes

2021-04-25 06:02 UTC, tdakkota commented on itertools.go
> +		panic(e)
I am not sure that we should use panics. It may produce an unexpected application crash.

For now, if callback returns an error, `map`/`filter` just stops the iteration. There is no way to return `error` from iterator,  so I created issue https://github.com/google/starlark-go/issues/366.

2021-04-25 14:52 UTC, Algebra8 commented on itertools.go
> +		panic(e)
Ah ok, so should I escape the error val or maybe just return false like [`filter` does](https://github.com/tdakkota/sun/blob/master/filter.go#L24)?

2021-04-26 16:08 UTC, Algebra8 commented
I just noticed that tests were breaking because of returning [`"count(1)"`](https://github.com/tdakkota/sun/pull/12#discussion_r619754902) when it should return `fmt.Sprintf("count("%v")", co.cnt.String())`.

Commit b847cb7c86286ca5690bf2270d03552ff905ca40 should fix this issue and all tests should pass :)

2021-04-26 19:49 UTC, tdakkota commented
Thanks!

2021-04-26 19:50 UTC, tdakkota approved these changes

2021-04-26 19:50 UTC, merged